import keyMirror from 'key-mirror';

export default keyMirror({
    TIP: null,
    THEME: null,
    
    AD: null,
    ADS:null,
    AD_POPUP:null,
    AD_USER:null,
    AD_MALL: null,

    GIFT: null,
    CONFIG: null,
    UPLOAD: null,
    OSS: null,
    PCOMMENT:null,
    PCOMMENTTOP:null,
    
    TOKEN: null,
    LOGIN: null,
    LOGIN_APPLE: null,
    REGISTER: null,
    VCODE: null,
    CODE_VALID: null,
    PWD_RESET: null,
    LOGOUT: null,
    LOGIN_WECHAT: null,
    LOGIN_WECHATR: null,
    LOGING_WECHATR:null,
    MOBILE_BIND: null,
    APPLE_MOBILE_BIND: null,

    SITE_MENU: null,
    SITE_INDEX: null,
    SITE_CHANNEL: null,
    SITE_ABOUT: null,

    SEARCH: null,
    SEARCH_COURSE: null,

    COURSE_COMMENT_PUBLISH:null,
    COMMENT_PUBLISH:null,
    INDEX:null,

    CHANNEL: null,
    
    LIVE: null,
    LIVE_REPLAY:null,

    COURSE_CHANNEL: null,
    COURSE_CATEGORY: null,
    COURSE: null,
    COURSES:null,
    COURSE_RECOMM:null,
    COURSE_INFO:null,
    COURSE_INFO_SCORE:null,
    COURSE_COMMENT: null,
    COURSE_COMMENT_RECOMM:null,
    COURSE_GOODS: null,
    COURSE_REWARD: null,
    COURSE_COLLECT: null,
    COURSE_COLLECT_REMOVE: null,
    COURSE_COLLECTS_REMOVE: null,
    COURSE_BOOK: null,
    COURSE_VERIFY: null,
    COURSE_LEARN: null,
    COURSE_PAY:null,
    COURSE_CAN_PLAY:null,
    COURSE_VIDEO:null,
    
    TEACHER: null,
    TEACHER_DESC: null,
    TEACHER_CHANNEL: null,
    TEACHER_RECOMM:null,
    TEACHER_FOLLOW: null,
    TEACHER_FOLLOW_REMOVE: null,
    TEACHER_ARTICLE: null,
    TEACHER_APPLY: null,
    TEACHER_STATUS: null,
    TEACHER_COURSE: null,
    LEADER_RECOMM: null,

    ARTICLE: null,
    ARTICLE_RECOMM: null,
    ARTICLE_CHANNEL: null,
    ARTICLE_RELATION: null,
    ARTICLE_COMMENT: null,
    ARTICLE_COMMENT_RECOMM:null,
    ARTICLE_LIKE: null,
    ARTICLE_LIKE_REMOVE: null,
    ARTICLE_SQUAD:null,
    ARTICLE_VOTE:null,
    
    ACTIVITY_CHANNEL:null,
    PROJECT_CHANNEL:null,

    RANK_INTEGRAL:null,
    RANK_MONTH:null,
    RANK_TOTAL:null,
    STUDY:null,
    STUDY_COURSE:null,
    STUDY_MAP:null,
    STUDY_REGION:null,
    STUDY_RANK:null,
    STUDY_MAP_JUDGE:null,

    USER:null,
    USER_PROFILE:null,
    USER_REGION: null,
    USER_PWD:null,
    USER_LEVEL:null,
    PROFILE:null,

    USER_INTEGRAL:null,
    USER_COUPON:null,

    EXAMPAPER:null,
    USER_BLACK:null,
    BLACK:null,
    USERCOURSE:null,
    USERSTUDY:null,
    USER_LOG:null,

    MSG_UNREAD:null,
    MSG:null,
    REMIND:null,
    MSG_READ:null,
    REMIND_COURSE:null,
    REMIND_ADMIN:null,
    MSG_OPERATE:null,
    MSG_CHAT:null,
    EDITMOBILE:null,

    COLLECT_REMOVE:null,

    LIKE_PUBLISH:null,
    LIKE_REMOVE:null,

    REWARD_PUBLISH:null,

    USERAUTH:null,
    FEEDBACK:null,
    PUSHFEEDBACK:null,
    CATEFEEDBACK:null,
    CATEQUESTION:null,
    CONFIGHELP:null,
    USERCOLLECT:null,
    USERACOLLECT:null,
    USERCERT:null,
    USERCONTENT:null,
    USERAGENT:null,

    USERCARD:null,
    USERMEDAL:null,
    SIGNIN:null,
    SIGNINS:null,
    USERREWARD:null,
    USERFOLLOW:null,
    USERFOLLOWS:null,
    REMOVEFOLLOW:null,
    AUSERFOLLOW:null,
    AREMOVEFOLLOW:null,

    ACTIVITYFLOP:null,
    LOTTERYREWORD:null,
    LOTTERYRECEIVE:null,
    ACTIVITYLOTTERY:null,
    USERTASK:null,
    INVITESTAT:null,
    USERINVITE:null,
    INVITECODE:null,
    INVITEIMGS:null,

    HELP:null,
    TEACHERUPINFO:null,
    USER_ACOLLECT:null,
    USER_AREMOVECOLLECT:null,
    CHECKO_TWO:null,
    STATUS_LEVEL:null,
    TEST_SCORE:null,
    EMS_GET:null,
    COURSE_SURVEY:null,
    USERBILLS:null,
    GETREGION:null,
    BANGDAN:null,
    FORLOTTERY:null,
    LIVEACTIVITYS:null,
    VANTLIVE:null,
    COMPANYLIST:null,

    //activity
    ACTIVITY: null,
    ACTIVITY_PAPER: null,
    ACTIVITY_ANSWER: null,
    ACTIVITY_JOIN: null,
    ACTIVITY_JOIN_INFO:null,
    ACTIVITY_VOTE_PUBLISH:null,
    ACTIVITY_VOTE:null,
    LOTTERYINFO:null,

    //O2O
    O2O:null,
    O2O_SKILL:null,
    O2O_DETAIL:null,
    O2O_SQUAD:null,
    O2O_VIDEO:null,
    O2O_TOPIC:null,
    O2O_EXAMPAPER:null,
    SQUARD_APPLY:null,
    SQUARD_CERT:null,
    CONFIG_CATENEWCERT:null,
    STUDY_STATUS:null,
    STUDY_INFO:null,
    TOPIC_ANSWER:null,
    TEST_INFO:null,
    USER_EXAM:null,
    PRIVILEGES:null,
    SQUAD_APPLYS:null,
    COURSE_MAP_DARY:null,

    //试卷
    EXAM_PAPER: null,
    EXAM_TEST: null,
    EXAM_REVIEW: null,
    EXAM_ANSWER: null,

    //地址
    ADDRESS:null,
    ADDRESS_DONE:null,
    ADDRESS_FIRST:null,
    ADDRESS_REMOVE:null,
    ADDRESS_INFO:null,

    //问吧
    ASK_CATEGORY: null,
    ASK_CHANNEL: null,
    ASK_SIMILAR: null,
    ASK: null,
    ASK_PUBLISH: null,
    ASK_INVITE: null,
    ASK_REPLY: null,
    ASK_ANSWER: null,
    ASK_ACTION: null,
    ASK_CONFIRM: null,
    ASK_COMMENT: null,
    ASK_FOLLOW: null,
    ASK_USER: null,
    ASK_USER_PUBLISH: null,
    ASK_USER_ANSWER: null,

    //商城
    SHOP_CATEGORY:null,
    SHOP_SEARCH:null,
    SHOP_SEARCHS:null,
    GOODS:null,
    GOODS_SUBMIT:null,
    ORDER:null,
    ORDER_DETAIL:null,
    ORDER_RETURN:null,
    ORDER_CONFIRM:null,
    ORDER_CANCEL:null,
    ORDER_SHIP:null,

    MALL_VIPENJOY:null,
    MALL_LECTENJECT:null,
    MALL_NEWRECOMM:null,
    MALL_LIMITGOODS:null,
    MALL_LIMITGOODSS:null,
    MALL_EXCHANGE:null,
    MALL_SELLTOP:null,
    MALL_CART_ADD:null,
    MALL_CART:null,
    MALL_CART_SETTLEMENT:null,
    MALL_CART_CLEAR:null,
    MALL_CART_REMOVE:null,
    MALL_CART_UPDATE:null,
    MALL_ORDER_TOPAY:null,
    MALL_ORDER_INVOICE:null,
    MALL_ORDER_SETSHOP:null,
    MALL_SHOP_AMOUNT:null,

    //PK赛场
    PKER_ACCOUNT: null,
    PKER_CATEGORY: null,
    PKER_CONFIG: null,
    PKER_LEVEL: null,
    PKER_RANK: null,
    PKER_TOPIC: null,
    PKER_TOPIC_PUBLISH: null,
    PKER_USER_TOPIC: null,
    PKER_MATCH: null,
    PKER_MATCH_AWARD: null,
    PKER_MATCH_RANK:null,
    PKER_MATCH_LIFE: null,

    //充值
    CHARGE:null,
    CHARGE_PAY:null,

    //下载
    DOWNLOAD_INDEX: null,
    DOWNLOAD: null,
    DOWNLOAD_LIKE: null,
    DOWNLOAD_UNLIKE: null,

    //完美林
    FOREST_INIT: null,
    FOREST_INDEX: null,
    FOREST_CERT: null,
    FOREST_SHOP: null,
    FOREST_ORDER: null,
    FOREST_USER_ORDER: null,
    FOREST_PICK: null,
    FOREST_QA: null,
    FOREST_SEEDS: null,
    FOREST_SEED: null,
    FOREST_SHARE: null,
    FOREST_STEAL: null,
    FOREST_WATER: null,
    FOREST_CONNECT: null,
    FOREST_FRIEND: null,

    //研讨会
    MEET_COND: null,
    MEET_TRAVEL: null,
    MEET_RITE: null,
    MEET_EXCHANGE: null,
    MEET_LIVE: null,
    MEET_LIVEBACK: null,
    MEET_TASK: null,
    MEET_PAPER: null,
    MEET_MOMENT_CHANNEL: null,
    MEET_MOMENT_PIC: null,
    MEET_MOMENT_VIDEO: null,
    MEET_MOMENT: null,
    MEET_WALL: null,
    MEET_WALL_INFO: null,
    MEET_WALL_PUBLISH: null,
    MEET_WALL_REMOVE: null,
    MEET_WALL_BG: null,
    MEET_WALL_UPLOADBG: null,
    MEET_WALL_LIKE: null,
    MEET_WALL_UNLIKE: null,
});
