//首页直播

export const home = {

    live_list:[{
        type:0,
        learn:3442,
        order:0,
        title:'可爱为什么是一种高效社交？',
        summary:'今天带您学习怎么跟陌生人说话',
        time:'',
    },{
        type:1,
        learn:0,
        order:3442,
        title:'可爱为什么是一种高效社交？',
        summary:'今天带您学习怎么跟陌生人说话',
        time:'今天19:00',
    }],

    consult:[{
        type:0,
        title:'第五届完美公益影像节中山完美绽放',
        eval:20,
        time:'1天前',
    },{
        type:1,
        title:'致敬最美追梦人',
        eval:20,
        time:'1天前',
    },{
        type:2,
        title:'第五届完美公益影像节',
        eval:20,
        time:'1天前',
    }],

    leader:[{
        name:'古润金',
        title:'董事长',
    },{
        name:'许国伟',
        title:'副董事长',
    },{
        name:'胡瑞连',
        title:'副董事长',
    }],

    project:[{
        title:'完美公司获颁“公益实践贡献奖',
        summary:'做公益和做企业一样，都要不忘初心，聚力前行！',
        begin:'2019.1.1',
        end:'2019.12.1',
    },{
        title:'完美公司获颁“公益实践贡献奖',
        summary:'做公益和做企业一样，都要不忘初心，聚力前行！',
        begin:'2019.1.1',
        end:'2019.12.1',
    }],

    graphic:[{
        type:0,
        author:'史振中',
        avatar:'',
        date:'2018年12月18日',
        title:'风光摄影基础：拍摄前需了解这些知识',
        summary:'一改以往教科书式的教学模式，告别枯燥的理论、数字和公式，把风光摄影基础知识和常用技巧',
        desc:'一改以往教科书式的教学模式，告别枯燥的理论、数字和公式，把风光摄影基础知识和常用技巧 数字和公式，把风光摄影基础知识和常用技巧，数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧。',
        parise:10,
        eval:12,
        images:['','',''],
    },{
        type:1,
        author:'史振中',
        avatar:'',
        date:'2018年12月18日',
        title:'风光摄影基础：拍摄前需了解这些知识',
        summary:'一改以往教科书式的教学模式，告别枯燥的理论、数字和公式，把风光摄影基础知识和常用技巧',
        desc:'一改以往教科书式的教学模式，告别枯燥的理论、数字和公式，把风光摄影基础知识和常用技巧 数字和公式，把风光摄影基础知识和常用技巧，数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧。',
        parise:10,
        eval:12,
        images:['','',''],
    },{
        type:2,
        author:'史振中',
        avatar:'',
        date:'2018年12月18日',
        title:'风光摄影基础：拍摄前需了解这些知识',
        summary:'一改以往教科书式的教学模式，告别枯燥的理论、数字和公式，把风光摄影基础知识和常用技巧',
        desc:'一改以往教科书式的教学模式，告别枯燥的理论、数字和公式，把风光摄影基础知识和常用技巧 数字和公式，把风光摄影基础知识和常用技巧，数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧。',
        parise:10,
        eval:12,
        images:['','',''],
    },{
        type:3,
        author:'史振中',
        avatar:'',
        date:'2018年12月18日',
        title:'风光摄影基础：拍摄前需了解这些知识',
        summary:'一改以往教科书式的教学模式，告别枯燥的理论、数字和公式，把风光摄影基础知识和常用技巧',
        desc:'一改以往教科书式的教学模式，告别枯燥的理论、数字和公式，把风光摄影基础知识和常用技巧 数字和公式，把风光摄影基础知识和常用技巧，数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧数字和公式，把风光摄影基础知识和常用技巧。',
        parise:10,
        eval:12,
        images:['','',''],
    }],
};


export const mail = {
    cart_list : [{
        activityId:0,
        attrId: "433",
        canHandsel: 0,
        cartId: 8,
        ctype: 0,
        deviceId: "0",
        goodsAmount: 100,
        goodsAttr: "包装2",
        goodsAttrList: [],
        goodsId: 80,
        goodsImg: "https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/1604641779089.jpg",
        goodsName: "完美马克杯",
        goodsNumber: 2,
        goodsWeight: 1,
        isFail: false,
        marketAmount: 132,
        price: null,
        userId: 25,
        warehouseId: 0
    },{
        activityId:1,
        attrId: "433",
        canHandsel: 0,
        cartId: 9,
        ctype: 0,
        deviceId: "0",
        goodsAmount: 100,
        goodsAttr: "包装2",
        goodsAttrList: [],
        goodsId: 81,
        goodsImg: "https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/1604641779089.jpg",
        goodsName: "完美马克杯",
        goodsNumber: 2,
        goodsWeight: 1,
        isFail: false,
        marketAmount: 132,
        price: null,
        userId: 25,
        warehouseId: 0
    },{
        activityId:2,
        attrId: "433",
        canHandsel: 0,
        cartId: 7,
        ctype: 0,
        deviceId: "0",
        goodsAmount: 100,
        goodsAttr: "包装2",
        goodsAttrList: [],
        goodsId: 82,
        goodsImg: "https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/1604641779089.jpg",
        goodsName: "完美马克杯",
        goodsNumber: 2,
        goodsWeight: 1,
        isFail: false,
        marketAmount: 132,
        price: null,
        userId: 25,
        warehouseId: 0
    },{
        activityId:1,
        attrId: "433",
        canHandsel: 0,
        cartId: 6,
        ctype: 0,
        deviceId: "0",
        goodsAmount: 100,
        goodsAttr: "包装2",
        goodsAttrList: [],
        goodsId: 83,
        goodsImg: "https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/1604641779089.jpg",
        goodsName: "完美马克杯",
        goodsNumber: 2,
        goodsWeight: 1,
        isFail: false,
        marketAmount: 132,
        price: null,
        userId: 25,
        warehouseId: 0
    },{
        activityId:2,
        attrId: "433",
        canHandsel: 0,
        cartId: 5,
        ctype: 0,
        deviceId: "0",
        goodsAmount: 100,
        goodsAttr: "包装2",
        goodsAttrList: [],
        goodsId: 84,
        goodsImg: "https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/1604641779089.jpg",
        goodsName: "完美马克杯",
        goodsNumber: 2,
        goodsWeight: 1,
        isFail: false,
        marketAmount: 132,
        price: null,
        userId: 25,
        warehouseId: 0
    },{
        activityId:2,
        attrId: "433",
        canHandsel: 0,
        cartId: 4,
        ctype: 0,
        deviceId: "0",
        goodsAmount: 100,
        goodsAttr: "包装2",
        goodsAttrList: [],
        goodsId: 85,
        goodsImg: "https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/1604641779089.jpg",
        goodsName: "完美马克杯",
        goodsNumber: 2,
        goodsWeight: 1,
        isFail: false,
        marketAmount: 132,
        price: null,
        userId: 25,
        warehouseId: 0
    },{
        activityId:0,
        attrId: "433",
        canHandsel: 0,
        cartId: 3,
        ctype: 0,
        deviceId: "0",
        goodsAmount: 100,
        goodsAttr: "包装2",
        goodsAttrList: [],
        goodsId: 86,
        goodsImg: "https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/1604641779089.jpg",
        goodsName: "完美马克杯",
        goodsNumber: 2,
        goodsWeight: 1,
        isFail: false,
        marketAmount: 132,
        price: null,
        userId: 25,
        warehouseId: 0
    }],

    activity_list : [{
        "activityId": 1,
        "title": "满减活动",
        "beginTime": 0,
        "endTime": 0,
        "condFir": "300",
        "condSec": "100",
        "way": 0,
        "goodsLimit": 0
      },
      {
        "activityId": 2,
        "title": "折扣活动",
        "beginTime": 0,
        "endTime": 0,
        "condFir": "3",
        "condSec": "0.8",
        "way": 1,
        "goodsLimit": 0
      }],

    arr:[{
        goodsNumber: 1,
        goodsAmount: 100,
        goodsId: 86,
    },{
        goodsNumber: 1,
        goodsAmount: 100,
        goodsId: 85,
    },{
        goodsNumber: 1,
        goodsAmount: 100,
        goodsId: 84,
    },{
        goodsNumber: 1,
        goodsAmount: 100,
        goodsId: 83,
    }],

}
